title:            DNS 차단 알림 사이트
description:      DNS 차단 알림 사이트
disqus_shortname:
reading_time:     true
words_per_minute: 100
# Your site's domain goes here (eg: https://mmistakes.github.io, http://yourdomain.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: https://warning.id

# Owner/author information
owner:
  name:           Warning Monster
  avatar:         domPerinon-2004.jpg
  bio:            "정보 공유와 관련 생태계에 관심이 많습니다. 근래의 정보 통제 사태가 아쉽습니다."
  email:          warningmonster.com@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  facebook:
  github:
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +mmistakes
  google_plus:

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-128216125-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Seoul
future:      false  # publish future dated posts --  true, false (default)
highlighter: rouge
markdown:    kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 20

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

# 2018.11.04 검색엔진 기능 추가
# Tipue search settings
tipue_search:
  include:                # 포함할 url을 선택한다.
    pages: true           # posts 폴더 이외에 다른 문서 선택 여부 (true일 경우 모든 url이 포함된다.)
  exclude:                # 제외시킬 url을 선택한다.
    files: [search.html]
    categories: []
    tags: []
# End of 검색엔진 기능 추가

excerpt_separator: <!--more-->

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
